[package]
name = "vulkanblackandwhite"
version = "0.1.0"
authors = ["alphastrata <alphastrata@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.13"
vulkano-shaders = "0.13"
vulkano-win = "0.13"
image = "0.21"
winit = "0.19"
stopwatch = "*"